MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 4
  ROI_HEADS:
    NAME: "RelationROIHeads"
    BATCH_SIZE_PER_IMAGE: 300
    NUM_CLASSES: 20
    IOU_THRESHOLDS: [0.5]
    IOU_LABELS: [0, 1]
    PROPOSAL_APPEND_GT: False
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  RPN:
    POST_NMS_TOPK_TRAIN: 300
    POST_NMS_TOPK_TEST: 300
    LOSS_WEIGHT: 3.0
    BATCH_SIZE_PER_IMAGE: 256
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TEST: ("voc_2007_test",)
SOLVER:
  IMS_PER_BATCH: 4
  GAMMA: 0.1
  BASE_LR: 0.002
  STEPS: (12000, 16000)
  MAX_ITER: 18000
VERSION: 2
OUTPUT_DIR: "./output/relationnet"
